### ISSUE TITLE
Add training module for using the METviewer Docker container.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus-Training#10]
## Describe the New Training Module ##
On 9/4/20, John HG, Jonathan Vigh, and Tara met with Frank from NOAA/SWPC. Frank would like to run the METviewer Docker container on his laptop to load some MET output files and plot them using METviewer. Instructions for this do exist, but on within the context of the container-dtc-nwp tutorial. For example:
http://dtcenter.org/tutorial-version-3/hurricane-sandy-case-27-oct-2012/visualize-verification-results

This task it to develop instructions, along with a training video, for visualizing MET output using the METviewer container. In particular, make the loading step as easy as possible. For sample input test data, consider loading the data generated by MET's "make test" command which writes output in the "out" directory.

Note that these details are also needed by Hank Fisher for his application of METplus on AWS for the Air Force project.

Have Frank test and refine these instructions.

### Acceptance Criteria ###
Input test data is just the .stat output files generated by running "make test".
The result should be an easy to follow set of instructions for running METviewer in this way.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new training module down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Training Module Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Identify required input data and update input datasets, as needed.
- [ ] Develop and test the new training module contents.
- [ ] Record the training module video and post to DTC channel.
- [ ] Include video link in the training module.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
In dtcenter/METviewer#166 I updated METviewer to automatically build Docker images from multiple branches/tags. These changes impact the instructions for using METviewer via a Docker container.

**Comment by JohnHalleyGotway** [comment]
METviewer Docker container commands:

- Check that Docker is working.
```
docker hello-world
```
- Clone the METviewer repo.
```
git checkout https://github.com/dtcenter/METviewer
cd METviewer/docker
```
- Setup the environment.
```
export METVIEWER_DOCKER_IMAGE=dtcenter/metviewer
export MYSQL_DIR=`pwd`/mysql
export METVIEWER_DIR=`pwd`/output
export METVIEWER_DATA=`pwd`/input
mkdir -p $MYSQL_DIR $METVIEWER_DIR $METVIEWER_DATA
```
- Launch METviewer.
```
./check_env.sh && docker-compose up -d
```
- Navigate to http://localhost:8080/metviewer/metviewer1.jsp
- Load sample data into a database.
```
ADD COMMANDS HERE
```
