### ISSUE TITLE
Add training module about the MET configuration options for climatology data.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus-Training#14]
## Describe the New Training Module ##
Binbin Zhou from NOAA/EMC wrote MET-Help with questions about how to configure Ensemble-Stat for using climatology data:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=98116

This would be a great topic for a new METplus-Training video. Recommend that we gather examples of how climatology data can be stored including examples of:
- data for each month of the year with 4 hours of the day
- data for each day of the year with 2 or 4 hours of the day
- data for each day of the year with 1 hour of the day
- how to use persistence data where the timestamp should NOT be checked

Be sure to clearly show how day_interval and hour_interval should be set for each.

### Acceptance Criteria ###
Need to gather sample climo datasets, including old 2.5 degree monthly data from NOAA/EMC, new 1.0 degree daily data from NOAA/EMC, Air Force uses persistence (I believe), and ECMWF and/or WMO (?) climo data.

### Time Estimate ###
3 days(?)

### Sub-Issues ###
Consider breaking the new training module down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
After the METplus-4.0 release but prior to the METplus-4.1 release.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## New Training Module Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Identify required input data and update input datasets, as needed.
- [ ] Develop and test the new training module contents.
- [ ] Record the training module video and post to DTC channel.
- [ ] Include video link in the training module.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
