### ISSUE TITLE
Add training module for the METplus tutorial setup.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus-Training#2]
## Describe the New Training Module ##

An initial version of the training module explaining how to get up and running with the METplus Practical Exercises already exists in
https://github.com/dtcenter/METplus-Training/blob/develop/docs/modules/METplus/tutorial_setup.rst

This task is at:
- add/edit content to this training
- test the instructions to ensure accuracy
- record the video version, post to YouTube, and the link to the module

Please see original training script in Google Docs here:
https://docs.google.com/document/d/1TkofLbiSwkfA17MpOBjpAYvlVNzyJl0cCc8zA6ClzyY/edit#

### Acceptance Criteria ###
*List input data types and sources.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new training module down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Training Module Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Identify required input data and update input datasets, as needed.
- [ ] Develop and test the new training module contents.
- [x] Record the training module video and post to DTC channel.
- [x] Include video link in the training module.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [x] Close this issue.

**Comment by bikegeek** [comment]
video uploaded to YouTube DTC channel with appropriate links and thumbnail on 1/13/2021
