### ISSUE TITLE
Add training module to demonstrate using the existing builds page to set up your environment.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus-Training#27]
## Describe the New Training Module ##
The METplus-Training site currently includes a placeholder to describe the METplus training environment on Cheyenne:
https://metplus-training.readthedocs.io/en/latest/modules/Environment/cheyenne.html

Recommend that we change the topic from being Cheyenne-specific to instead demonstrate the contents of the "Existing Builds" page. The video could include examples of copy/pasting the commands for loading the MET/METplus modules on Cheyenne and Hera, but those are just examples. We want to teach users how to use the info on those pages to run MET/METplus on multiple machines.

If possible, try to make the video version-agnostic. While we'll obviously use the current version, emphasize that the same process should work for future versions as well.

### Acceptance Criteria ###
*List input data types and sources.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new training module down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793521

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Training Module Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Identify required input data and update input datasets, as needed.
- [ ] Develop and test the new training module contents.
- [ ] Record the training module video and post to DTC channel.
- [ ] Include video link in the training module.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
