### ISSUE TITLE
Add training module for common METplus configuration variables.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus-Training#5]
## Describe the New Training Module ##

An initial version of the training module explaining common METplus configuration variables already exists
https://github.com/dtcenter/METplus-Training/blob/develop/docs/modules/METplus/common_config_vars.rst

This task is at:
- add/edit content to this training
- test the instructions to ensure accuracy
- record the video version, post to YouTube, and the link to the module

Please see original training script in Google Docs here:
https://docs.google.com/document/d/1mmNoywmkaMm95xS5vKoKA0sq9WgG6O3XRCJxPZa5-Ow/edit

### Acceptance Criteria ###
*List input data types and sources.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new training module down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Training Module Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Identify required input data and update input datasets, as needed.
- [ ] Develop and test the new training module contents.
- [ ] Record the training module video and post to DTC channel.
- [ ] Include video link in the training module.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
There is a lot of content to cover for common config variables. I am breaking this into multiple videos: Part 1 focuses on timing (in progress). Part 2 can focus on field info ([FCST/OBS]_VAR<n>_[NAME/LEVEL/THRESH/OPTIONS]). Part 3 could focus on directory and filename template information, although this could also be covered in the Example wrapper video (#6 )

**Comment by georgemccabe** [comment]
Part 1 is complete.

**Comment by georgemccabe** [comment]
Videos are complete. Still need to upload additional files such as images used in the videos and rearranged directories to include a sub-directory for each video's supplemental content.

**Comment by georgemccabe** [comment]
Added power point slides used to create METplus configuration and common config part 1 videos into docs/modules/METplus/metplus_configuration_files named metplus_configuration.pptx
